/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhoWeAreRouteImport } from './routes/who-we-are'
import { Route as ThinkingRouteImport } from './routes/thinking'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as ApproachRouteImport } from './routes/approach'
import { Route as IndexRouteImport } from './routes/index'

const WhoWeAreRoute = WhoWeAreRouteImport.update({
  id: '/who-we-are',
  path: '/who-we-are',
  getParentRoute: () => rootRouteImport,
} as any)
const ThinkingRoute = ThinkingRouteImport.update({
  id: '/thinking',
  path: '/thinking',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approach': typeof ApproachRoute
  '/cases': typeof CasesRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/submit': typeof SubmitRoute
  '/thinking': typeof ThinkingRoute
  '/who-we-are': typeof WhoWeAreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approach': typeof ApproachRoute
  '/cases': typeof CasesRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/submit': typeof SubmitRoute
  '/thinking': typeof ThinkingRoute
  '/who-we-are': typeof WhoWeAreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approach': typeof ApproachRoute
  '/cases': typeof CasesRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/submit': typeof SubmitRoute
  '/thinking': typeof ThinkingRoute
  '/who-we-are': typeof WhoWeAreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approach'
    | '/cases'
    | '/contact'
    | '/services'
    | '/submit'
    | '/thinking'
    | '/who-we-are'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approach'
    | '/cases'
    | '/contact'
    | '/services'
    | '/submit'
    | '/thinking'
    | '/who-we-are'
  id:
    | '__root__'
    | '/'
    | '/approach'
    | '/cases'
    | '/contact'
    | '/services'
    | '/submit'
    | '/thinking'
    | '/who-we-are'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApproachRoute: typeof ApproachRoute
  CasesRoute: typeof CasesRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  SubmitRoute: typeof SubmitRoute
  ThinkingRoute: typeof ThinkingRoute
  WhoWeAreRoute: typeof WhoWeAreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/who-we-are': {
      id: '/who-we-are'
      path: '/who-we-are'
      fullPath: '/who-we-are'
      preLoaderRoute: typeof WhoWeAreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thinking': {
      id: '/thinking'
      path: '/thinking'
      fullPath: '/thinking'
      preLoaderRoute: typeof ThinkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach': {
      id: '/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApproachRoute: ApproachRoute,
  CasesRoute: CasesRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  SubmitRoute: SubmitRoute,
  ThinkingRoute: ThinkingRoute,
  WhoWeAreRoute: WhoWeAreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
